version: "3.9"

services:
  api-devnet:
    image: node:18-alpine
    container_name: mint-price-api-devnet
    working_dir: /app
    volumes:
      - ./:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sh -c "corepack enable && yarn install --frozen-lockfile && yarn build && yarn start"
    ports:
      - "9091:9091"
    environment:
      - NETWORK=${NETWORK_DEVNET:-devnet}
      - PORT=${PORT_DEVNET:-9091}
      - GRAPHQL_ENDPOINT=${GRAPHQL_ENDPOINT_DEVNET:-https://graph-devnet.flipflop.plus/graphql}
      - POSTGRES_DB_URL=postgresql://${POSTGRES_DB_USER:-postgres}:${POSTGRES_DB_PASSWORD:-postgres}@${POSTGRES_DB_HOST:-host.docker.internal}:${POSTGRES_DB_PORT:-5433}/${POSTGRES_DB_NAME_DEVNET:-postgres}?sslmode=disable
      - API_KEYS=${API_KEYS:-}
      - ADMIN_API_KEYS=${ADMIN_API_KEYS:-}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
    restart: unless-stopped

  api-mainnet:
    image: node:18-alpine
    container_name: mint-price-api-mainnet
    working_dir: /app
    volumes:
      - ./:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sh -c "corepack enable && yarn install --frozen-lockfile && yarn build && yarn start"
    ports:
      - "9090:9090"
    environment:
      - NETWORK=${NETWORK_MAINNET:-mainnet}
      - PORT=${PORT_MAINNET:-9090}
      - GRAPHQL_ENDPOINT=${GRAPHQL_ENDPOINT_MAINNET:-https://graph-mainnet.flipflop.plus/graphql}
      - POSTGRES_DB_URL=postgresql://${POSTGRES_DB_USER:-postgres}:${POSTGRES_DB_PASSWORD:-postgres}@${POSTGRES_DB_HOST:-host.docker.internal}:${POSTGRES_DB_PORT:-5433}/${POSTGRES_DB_NAME_MAINNET:-postgres}?sslmode=disable
      - API_KEYS=${API_KEYS:-}
      - ADMIN_API_KEYS=${ADMIN_API_KEYS:-}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
    restart: unless-stopped